version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-app-image:latest
    command: ["/app"]
    pull_policy: build
    environment:
      - DISCORD_TOKEN=$DISCORD_TOKEN
      - COOLDOWN_ALLOW_LIST=$COOLDOWN_ALLOW_LIST