# fly.toml app configuration file generated for himbot on 2024-10-20T22:41:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'himbot'
primary_region = 'ord'

[build]

[[services]]
internal_port = 3000
protocol = "tcp"
min_machines_running = 1

[[vm]]
size = 'shared-cpu-1x'
