# fly.toml app configuration file generated for himbot on 2023-10-19T18:34:44-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "himbot"
primary_region = "sea"
swap_size_mb = 512

[http_service]
internal_port = 3000
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
