# fly.toml app configuration file generated for himbot on 2023-10-17T18:37:42-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "himbot"
primary_region = "sea"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
